spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.88.155:3306/testbase?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
  application:
    name: testcloud-dept
  jpa:
    show-sql: true
    open-in-view: true
  profiles: dev

server:
  port: 8001

feign:
  hystrix:
    enabled: true


info:
  app.name: atguigu-microservicecloud1
  company.name: www.atguigu.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}
